export const bibleData = [
	{
		testamentName: "Old Testament",
		selected: false,
		books: [
			{
				bookName: "Genesis",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
					{ chapter: 32, selected: false, completed: false },
					{ chapter: 33, selected: false, completed: false },
					{ chapter: 34, selected: false, completed: false },
					{ chapter: 35, selected: false, completed: false },
					{ chapter: 36, selected: false, completed: false },
					{ chapter: 37, selected: false, completed: false },
					{ chapter: 38, selected: false, completed: false },
					{ chapter: 39, selected: false, completed: false },
					{ chapter: 40, selected: false, completed: false },
					{ chapter: 41, selected: false, completed: false },
					{ chapter: 42, selected: false, completed: false },
					{ chapter: 43, selected: false, completed: false },
					{ chapter: 44, selected: false, completed: false },
					{ chapter: 45, selected: false, completed: false },
					{ chapter: 46, selected: false, completed: false },
					{ chapter: 47, selected: false, completed: false },
					{ chapter: 48, selected: false, completed: false },
					{ chapter: 49, selected: false, completed: false },
					{ chapter: 50, selected: false, completed: false },
				],
			},
			{
				bookName: "Exodus",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
					{ chapter: 32, selected: false, completed: false },
					{ chapter: 33, selected: false, completed: false },
					{ chapter: 34, selected: false, completed: false },
					{ chapter: 35, selected: false, completed: false },
					{ chapter: 36, selected: false, completed: false },
					{ chapter: 37, selected: false, completed: false },
					{ chapter: 38, selected: false, completed: false },
					{ chapter: 39, selected: false, completed: false },
					{ chapter: 40, selected: false, completed: false },
				],
			},
			{
				bookName: "Leviticus",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
				],
			},
			{
				bookName: "Numbers",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
					{ chapter: 32, selected: false, completed: false },
					{ chapter: 33, selected: false, completed: false },
					{ chapter: 34, selected: false, completed: false },
					{ chapter: 35, selected: false, completed: false },
					{ chapter: 36, selected: false, completed: false },
				],
			},
			{
				bookName: "Deuteronomy",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
					{ chapter: 32, selected: false, completed: false },
					{ chapter: 33, selected: false, completed: false },
					{ chapter: 34, selected: false, completed: false },
				],
			},
			{
				bookName: "Joshua",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
				],
			},
			{
				bookName: "Judges",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
				],
			},
			{
				bookName: "Ruth",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
				],
			},
			{
				bookName: "1 Samuel",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
				],
			},
			{
				bookName: "2 Samuel",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
				],
			},
			{
				bookName: "1 Kings",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
				],
			},
			{
				bookName: "2 Kings",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
				],
			},
			{
				bookName: "1 Chronicles",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
				],
			},
			{
				bookName: "2 Chronicles",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
					{ chapter: 32, selected: false, completed: false },
					{ chapter: 33, selected: false, completed: false },
					{ chapter: 34, selected: false, completed: false },
					{ chapter: 35, selected: false, completed: false },
					{ chapter: 36, selected: false, completed: false },
				],
			},
			{
				bookName: "Ezra",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
				],
			},
			{
				bookName: "Nehemiah",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
				],
			},
			{
				bookName: "Esther",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
				],
			},
			{
				bookName: "Job",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
					{ chapter: 32, selected: false, completed: false },
					{ chapter: 33, selected: false, completed: false },
					{ chapter: 34, selected: false, completed: false },
					{ chapter: 35, selected: false, completed: false },
					{ chapter: 36, selected: false, completed: false },
					{ chapter: 37, selected: false, completed: false },
					{ chapter: 38, selected: false, completed: false },
					{ chapter: 39, selected: false, completed: false },
					{ chapter: 40, selected: false, completed: false },
					{ chapter: 41, selected: false, completed: false },
					{ chapter: 42, selected: false, completed: false },
				],
			},
			{
				bookName: "Psalms",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
					{ chapter: 32, selected: false, completed: false },
					{ chapter: 33, selected: false, completed: false },
					{ chapter: 34, selected: false, completed: false },
					{ chapter: 35, selected: false, completed: false },
					{ chapter: 36, selected: false, completed: false },
					{ chapter: 37, selected: false, completed: false },
					{ chapter: 38, selected: false, completed: false },
					{ chapter: 39, selected: false, completed: false },
					{ chapter: 40, selected: false, completed: false },
					{ chapter: 41, selected: false, completed: false },
					{ chapter: 42, selected: false, completed: false },
					{ chapter: 43, selected: false, completed: false },
					{ chapter: 44, selected: false, completed: false },
					{ chapter: 45, selected: false, completed: false },
					{ chapter: 46, selected: false, completed: false },
					{ chapter: 47, selected: false, completed: false },
					{ chapter: 48, selected: false, completed: false },
					{ chapter: 49, selected: false, completed: false },
					{ chapter: 50, selected: false, completed: false },
					{ chapter: 51, selected: false, completed: false },
					{ chapter: 52, selected: false, completed: false },
					{ chapter: 53, selected: false, completed: false },
					{ chapter: 54, selected: false, completed: false },
					{ chapter: 55, selected: false, completed: false },
					{ chapter: 56, selected: false, completed: false },
					{ chapter: 57, selected: false, completed: false },
					{ chapter: 58, selected: false, completed: false },
					{ chapter: 59, selected: false, completed: false },
					{ chapter: 60, selected: false, completed: false },
					{ chapter: 61, selected: false, completed: false },
					{ chapter: 62, selected: false, completed: false },
					{ chapter: 63, selected: false, completed: false },
					{ chapter: 64, selected: false, completed: false },
					{ chapter: 65, selected: false, completed: false },
					{ chapter: 66, selected: false, completed: false },
					{ chapter: 67, selected: false, completed: false },
					{ chapter: 68, selected: false, completed: false },
					{ chapter: 69, selected: false, completed: false },
					{ chapter: 70, selected: false, completed: false },
					{ chapter: 71, selected: false, completed: false },
					{ chapter: 72, selected: false, completed: false },
					{ chapter: 73, selected: false, completed: false },
					{ chapter: 74, selected: false, completed: false },
					{ chapter: 75, selected: false, completed: false },
					{ chapter: 76, selected: false, completed: false },
					{ chapter: 77, selected: false, completed: false },
					{ chapter: 78, selected: false, completed: false },
					{ chapter: 79, selected: false, completed: false },
					{ chapter: 80, selected: false, completed: false },
					{ chapter: 81, selected: false, completed: false },
					{ chapter: 82, selected: false, completed: false },
					{ chapter: 83, selected: false, completed: false },
					{ chapter: 84, selected: false, completed: false },
					{ chapter: 85, selected: false, completed: false },
					{ chapter: 86, selected: false, completed: false },
					{ chapter: 87, selected: false, completed: false },
					{ chapter: 88, selected: false, completed: false },
					{ chapter: 89, selected: false, completed: false },
					{ chapter: 90, selected: false, completed: false },
					{ chapter: 91, selected: false, completed: false },
					{ chapter: 92, selected: false, completed: false },
					{ chapter: 93, selected: false, completed: false },
					{ chapter: 94, selected: false, completed: false },
					{ chapter: 95, selected: false, completed: false },
					{ chapter: 96, selected: false, completed: false },
					{ chapter: 97, selected: false, completed: false },
					{ chapter: 98, selected: false, completed: false },
					{ chapter: 99, selected: false, completed: false },
					{ chapter: 100, selected: false, completed: false },
					{ chapter: 101, selected: false, completed: false },
					{ chapter: 102, selected: false, completed: false },
					{ chapter: 103, selected: false, completed: false },
					{ chapter: 104, selected: false, completed: false },
					{ chapter: 105, selected: false, completed: false },
					{ chapter: 106, selected: false, completed: false },
					{ chapter: 107, selected: false, completed: false },
					{ chapter: 108, selected: false, completed: false },
					{ chapter: 109, selected: false, completed: false },
					{ chapter: 110, selected: false, completed: false },
					{ chapter: 111, selected: false, completed: false },
					{ chapter: 112, selected: false, completed: false },
					{ chapter: 113, selected: false, completed: false },
					{ chapter: 114, selected: false, completed: false },
					{ chapter: 115, selected: false, completed: false },
					{ chapter: 116, selected: false, completed: false },
					{ chapter: 117, selected: false, completed: false },
					{ chapter: 118, selected: false, completed: false },
					{ chapter: 119, selected: false, completed: false },
					{ chapter: 120, selected: false, completed: false },
					{ chapter: 121, selected: false, completed: false },
					{ chapter: 122, selected: false, completed: false },
					{ chapter: 123, selected: false, completed: false },
					{ chapter: 124, selected: false, completed: false },
					{ chapter: 125, selected: false, completed: false },
					{ chapter: 126, selected: false, completed: false },
					{ chapter: 127, selected: false, completed: false },
					{ chapter: 128, selected: false, completed: false },
					{ chapter: 129, selected: false, completed: false },
					{ chapter: 130, selected: false, completed: false },
					{ chapter: 131, selected: false, completed: false },
					{ chapter: 132, selected: false, completed: false },
					{ chapter: 133, selected: false, completed: false },
					{ chapter: 134, selected: false, completed: false },
					{ chapter: 135, selected: false, completed: false },
					{ chapter: 136, selected: false, completed: false },
					{ chapter: 137, selected: false, completed: false },
					{ chapter: 138, selected: false, completed: false },
					{ chapter: 139, selected: false, completed: false },
					{ chapter: 140, selected: false, completed: false },
					{ chapter: 141, selected: false, completed: false },
					{ chapter: 142, selected: false, completed: false },
					{ chapter: 143, selected: false, completed: false },
					{ chapter: 144, selected: false, completed: false },
					{ chapter: 145, selected: false, completed: false },
					{ chapter: 146, selected: false, completed: false },
					{ chapter: 147, selected: false, completed: false },
					{ chapter: 148, selected: false, completed: false },
					{ chapter: 149, selected: false, completed: false },
					{ chapter: 150, selected: false, completed: false },
				],
			},
			{
				bookName: "Proverbs",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
				],
			},
			{
				bookName: "Ecclesiastes",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
				],
			},
			{
				bookName: "Song of Solomon",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
				],
			},
			{
				bookName: "Isaiah",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
					{ chapter: 32, selected: false, completed: false },
					{ chapter: 33, selected: false, completed: false },
					{ chapter: 34, selected: false, completed: false },
					{ chapter: 35, selected: false, completed: false },
					{ chapter: 36, selected: false, completed: false },
					{ chapter: 37, selected: false, completed: false },
					{ chapter: 38, selected: false, completed: false },
					{ chapter: 39, selected: false, completed: false },
					{ chapter: 40, selected: false, completed: false },
					{ chapter: 41, selected: false, completed: false },
					{ chapter: 42, selected: false, completed: false },
					{ chapter: 43, selected: false, completed: false },
					{ chapter: 44, selected: false, completed: false },
					{ chapter: 45, selected: false, completed: false },
					{ chapter: 46, selected: false, completed: false },
					{ chapter: 47, selected: false, completed: false },
					{ chapter: 48, selected: false, completed: false },
					{ chapter: 49, selected: false, completed: false },
					{ chapter: 50, selected: false, completed: false },
					{ chapter: 51, selected: false, completed: false },
					{ chapter: 52, selected: false, completed: false },
					{ chapter: 53, selected: false, completed: false },
					{ chapter: 54, selected: false, completed: false },
					{ chapter: 55, selected: false, completed: false },
					{ chapter: 56, selected: false, completed: false },
					{ chapter: 57, selected: false, completed: false },
					{ chapter: 58, selected: false, completed: false },
					{ chapter: 59, selected: false, completed: false },
					{ chapter: 60, selected: false, completed: false },
					{ chapter: 61, selected: false, completed: false },
					{ chapter: 62, selected: false, completed: false },
					{ chapter: 63, selected: false, completed: false },
					{ chapter: 64, selected: false, completed: false },
					{ chapter: 65, selected: false, completed: false },
					{ chapter: 66, selected: false, completed: false },
				],
			},
			{
				bookName: "Jeremiah",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
					{ chapter: 32, selected: false, completed: false },
					{ chapter: 33, selected: false, completed: false },
					{ chapter: 34, selected: false, completed: false },
					{ chapter: 35, selected: false, completed: false },
					{ chapter: 36, selected: false, completed: false },
					{ chapter: 37, selected: false, completed: false },
					{ chapter: 38, selected: false, completed: false },
					{ chapter: 39, selected: false, completed: false },
					{ chapter: 40, selected: false, completed: false },
					{ chapter: 41, selected: false, completed: false },
					{ chapter: 42, selected: false, completed: false },
					{ chapter: 43, selected: false, completed: false },
					{ chapter: 44, selected: false, completed: false },
					{ chapter: 45, selected: false, completed: false },
					{ chapter: 46, selected: false, completed: false },
					{ chapter: 47, selected: false, completed: false },
					{ chapter: 48, selected: false, completed: false },
					{ chapter: 49, selected: false, completed: false },
					{ chapter: 50, selected: false, completed: false },
					{ chapter: 51, selected: false, completed: false },
					{ chapter: 52, selected: false, completed: false },
				],
			},
			{
				bookName: "Lamentations",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
				],
			},
			{
				bookName: "Ezekiel",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
					{ chapter: 29, selected: false, completed: false },
					{ chapter: 30, selected: false, completed: false },
					{ chapter: 31, selected: false, completed: false },
					{ chapter: 32, selected: false, completed: false },
					{ chapter: 33, selected: false, completed: false },
					{ chapter: 34, selected: false, completed: false },
					{ chapter: 35, selected: false, completed: false },
					{ chapter: 36, selected: false, completed: false },
					{ chapter: 37, selected: false, completed: false },
					{ chapter: 38, selected: false, completed: false },
					{ chapter: 39, selected: false, completed: false },
					{ chapter: 40, selected: false, completed: false },
					{ chapter: 41, selected: false, completed: false },
					{ chapter: 42, selected: false, completed: false },
					{ chapter: 43, selected: false, completed: false },
					{ chapter: 44, selected: false, completed: false },
					{ chapter: 45, selected: false, completed: false },
					{ chapter: 46, selected: false, completed: false },
					{ chapter: 47, selected: false, completed: false },
					{ chapter: 48, selected: false, completed: false },
				],
			},
			{
				bookName: "Daniel",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
				],
			},
			{
				bookName: "Hosea",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
				],
			},
			{
				bookName: "Joel",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
				],
			},
			{
				bookName: "Amos",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
				],
			},
			{
				bookName: "Obadiah",
				selected: false,
				chapters: [{ chapter: 1, selected: false, completed: false }],
			},
			{
				bookName: "Jonah",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
				],
			},
			{
				bookName: "Micah",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
				],
			},
			{
				bookName: "Nahum",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
				],
			},
			{
				bookName: "Habakkuk",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
				],
			},
			{
				bookName: "Zephaniah",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
				],
			},
			{
				bookName: "Haggai",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
				],
			},
			{
				bookName: "Zechariah",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
				],
			},
			{
				bookName: "Malachi",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
				],
			},
		],
	},
	{
		testamentName: "New Testament",
		selected: false,
		books: [
			{
				bookName: "Matthew",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
				],
			},
			{
				bookName: "Mark",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
				],
			},
			{
				bookName: "Luke",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
				],
			},
			{
				bookName: "John",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
				],
			},
			{
				bookName: "Acts",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
					{ chapter: 23, selected: false, completed: false },
					{ chapter: 24, selected: false, completed: false },
					{ chapter: 25, selected: false, completed: false },
					{ chapter: 26, selected: false, completed: false },
					{ chapter: 27, selected: false, completed: false },
					{ chapter: 28, selected: false, completed: false },
				],
			},
			{
				bookName: "Romans",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
				],
			},
			{
				bookName: "1 Corinthians",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
				],
			},
			{
				bookName: "2 Corinthians",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
				],
			},
			{
				bookName: "Galatians",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
				],
			},
			{
				bookName: "Ephesians",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
				],
			},
			{
				bookName: "Philippians",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
				],
			},
			{
				bookName: "Colossians",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
				],
			},
			{
				bookName: "1 Thessalonians",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
				],
			},
			{
				bookName: "2 Thessalonians",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
				],
			},
			{
				bookName: "1 Timothy",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
				],
			},
			{
				bookName: "2 Timothy",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
				],
			},
			{
				bookName: "Titus",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
				],
			},
			{
				bookName: "Philemon",
				selected: false,
				chapters: [{ chapter: 1, selected: false, completed: false }],
			},
			{
				bookName: "Hebrews",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
				],
			},
			{
				bookName: "James",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
				],
			},
			{
				bookName: "1 Peter",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
				],
			},
			{
				bookName: "2 Peter",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
				],
			},
			{
				bookName: "1 John",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
				],
			},
			{
				bookName: "2 John",
				selected: false,
				chapters: [{ chapter: 1, selected: false, completed: false }],
			},
			{
				bookName: "3 John",
				selected: false,
				chapters: [{ chapter: 1, selected: false, completed: false }],
			},
			{
				bookName: "Jude",
				selected: false,
				chapters: [{ chapter: 1, selected: false, completed: false }],
			},
			{
				bookName: "Revelation",
				selected: false,
				chapters: [
					{ chapter: 1, selected: false, completed: false },
					{ chapter: 2, selected: false, completed: false },
					{ chapter: 3, selected: false, completed: false },
					{ chapter: 4, selected: false, completed: false },
					{ chapter: 5, selected: false, completed: false },
					{ chapter: 6, selected: false, completed: false },
					{ chapter: 7, selected: false, completed: false },
					{ chapter: 8, selected: false, completed: false },
					{ chapter: 9, selected: false, completed: false },
					{ chapter: 10, selected: false, completed: false },
					{ chapter: 11, selected: false, completed: false },
					{ chapter: 12, selected: false, completed: false },
					{ chapter: 13, selected: false, completed: false },
					{ chapter: 14, selected: false, completed: false },
					{ chapter: 15, selected: false, completed: false },
					{ chapter: 16, selected: false, completed: false },
					{ chapter: 17, selected: false, completed: false },
					{ chapter: 18, selected: false, completed: false },
					{ chapter: 19, selected: false, completed: false },
					{ chapter: 20, selected: false, completed: false },
					{ chapter: 21, selected: false, completed: false },
					{ chapter: 22, selected: false, completed: false },
				],
			},
		],
	},
];
