const quizDataMapping = {
	Genesis: require("./quizData/GenesisQuiz.json"),
	// Exodus: require("./quizData/ExodusQuiz.json"),
	// Leviticus: require("./quizData/LeviticusQuiz.json"),
	// Numbers: require("./quizData/NumbersQuiz.json"),
	// Deuteronomy: require("./quizData/DeuteronomyQuiz.json"),
	// Joshua: require("./quizData/JoshuaQuiz.json"),
	// Judges: require("./quizData/JudgesQuiz.json"),
	// Ruth: require("./quizData/RuthQuiz.json"),
	// "1 Samuel": require("./quizData/1SamuelQuiz.json"),
	// "2 Samuel": require("./quizData/2SamuelQuiz.json"),
	// "1 Kings": require("./quizData/1KingsQuiz.json"),
	// "2 Kings": require("./quizData/2KingsQuiz.json"),
	// "1 Chronicles": require("./quizData/1ChroniclesQuiz.json"),
	// "2 Chronicles": require("./quizData/2ChroniclesQuiz.json"),
	// Ezra: require("./quizData/EzraQuiz.json"),
	// Nehemiah: require("./quizData/NehemiahQuiz.json"),
	// Esther: require("./quizData/EstherQuiz.json"),
	// Job: require("./quizData/JobQuiz.json"),
	// Psalms: require("./quizData/PsalmsQuiz.json"),
	// Proverbs: require("./quizData/ProverbsQuiz.json"),
	// Ecclesiastes: require("./quizData/EcclesiastesQuiz.json"),
	// "Song of Solomon": require("./quizData/SongOfSolomonQuiz.json"),
	// Isaiah: require("./quizData/IsaiahQuiz.json"),
	// Jeremiah: require("./quizData/JeremiahQuiz.json"),
	// Lamentations: require("./quizData/LamentationsQuiz.json"),
	// Ezekiel: require("./quizData/EzekielQuiz.json"),
	// Daniel: require("./quizData/DanielQuiz.json"),
	// Hosea: require("./quizData/HoseaQuiz.json"),
	// Joel: require("./quizData/JoelQuiz.json"),
	// Amos: require("./quizData/AmosQuiz.json"),
	// Obadiah: require("./quizData/ObadiahQuiz.json"),
	// Jonah: require("./quizData/JonahQuiz.json"),
	// Micah: require("./quizData/MicahQuiz.json"),
	// Nahum: require("./quizData/NahumQuiz.json"),
	// Habakkuk: require("./quizData/HabakkukQuiz.json"),
	// Zephaniah: require("./quizData/ZephaniahQuiz.json"),
	// Haggai: require("./quizData/HaggaiQuiz.json"),
	// Zechariah: require("./quizData/ZechariahQuiz.json"),
	// Malachi: require("./quizData/MalachiQuiz.json"),
	Matthew: require("./quizData/MatthewQuiz.json"),
	// Mark: require("./quizData/MarkQuiz.json"),
	// Luke: require("./quizData/LukeQuiz.json"),
	// John: require("./quizData/JohnQuiz.json"),
	// Acts: require("./quizData/ActsQuiz.json"),
	// Romans: require("./quizData/RomansQuiz.json"),
	// "1 Corinthians": require("./quizData/1CorinthiansQuiz.json"),
	// "2 Corinthians": require("./quizData/2CorinthiansQuiz.json"),
	// Galatians: require("./quizData/GalatiansQuiz.json"),
	// Ephesians: require("./quizData/EphesiansQuiz.json"),
	// Philippians: require("./quizData/PhilippiansQuiz.json"),
	// Colossians: require("./quizData/ColossiansQuiz.json"),
	// "1 Thessalonians": require("./quizData/1ThessaloniansQuiz.json"),
	// "2 Thessalonians": require("./quizData/2ThessaloniansQuiz.json"),
	// "1 Timothy": require("./quizData/1TimothyQuiz.json"),
	// "2 Timothy": require("./quizData/2TimothyQuiz.json"),
	// Titus: require("./quizData/TitusQuiz.json"),
	// Philemon: require("./quizData/PhilemonQuiz.json"),
	// Hebrews: require("./quizData/HebrewsQuiz.json"),
	// James: require("./quizData/JamesQuiz.json"),
	// "1 Peter": require("./quizData/1PeterQuiz.json"),
	// "2 Peter": require("./quizData/2PeterQuiz.json"),
	// "1 John": require("./quizData/1JohnQuiz.json"),
	// "2 John": require("./quizData/2JohnQuiz.json"),
	// "3 John": require("./quizData/3JohnQuiz.json"),
	// Jude: require("./quizData/JudeQuiz.json"),
	// Revelation: require("./quizData/RevelationQuiz.json"),
};
