export const quizMap = {
	Genesis: require("./quizzesByBook/GenesisQuiz.json"),
	Exodus: require("./quizzesByBook/ExodusQuiz.json"),
	Leviticus: require("./quizzesByBook/LeviticusQuiz.json"),
	Numbers: require("./quizzesByBook/NumbersQuiz.json"),
	Deuteronomy: require("./quizzesByBook/DeuteronomyQuiz.json"),
	Joshua: require("./quizzesByBook/JoshuaQuiz.json"),
	Judges: require("./quizzesByBook/JudgesQuiz.json"),
	Ruth: require("./quizzesByBook/RuthQuiz.json"),
	"1 Samuel": require("./quizzesByBook/1SamuelQuiz.json"),
	"2 Samuel": require("./quizzesByBook/2SamuelQuiz.json"),
	"1 Kings": require("./quizzesByBook/1KingsQuiz.json"),
	"2 Kings": require("./quizzesByBook/2KingsQuiz.json"),
	"1 Chronicles": require("./quizzesByBook/1ChroniclesQuiz.json"),
	"2 Chronicles": require("./quizzesByBook/2ChroniclesQuiz.json"),
	Ezra: require("./quizzesByBook/EzraQuiz.json"),
	Nehemiah: require("./quizzesByBook/NehemiahQuiz.json"),
	Esther: require("./quizzesByBook/EstherQuiz.json"),
	Job: require("./quizzesByBook/JobQuiz.json"),
	Psalms: require("./quizzesByBook/PsalmsQuiz.json"),
	Proverbs: require("./quizzesByBook/ProverbsQuiz.json"),
	Ecclesiastes: require("./quizzesByBook/EcclesiastesQuiz.json"),
	"Song of Solomon": require("./quizzesByBook/SongOfSolomonQuiz.json"),
	Isaiah: require("./quizzesByBook/IsaiahQuiz.json"),
	Jeremiah: require("./quizzesByBook/JeremiahQuiz.json"),
	Lamentations: require("./quizzesByBook/LamentationsQuiz.json"),
	Ezekiel: require("./quizzesByBook/EzekielQuiz.json"),
	Daniel: require("./quizzesByBook/DanielQuiz.json"),
	Hosea: require("./quizzesByBook/HoseaQuiz.json"),
	Joel: require("./quizzesByBook/JoelQuiz.json"),
	Amos: require("./quizzesByBook/AmosQuiz.json"),
	Obadiah: require("./quizzesByBook/ObadiahQuiz.json"),
	Jonah: require("./quizzesByBook/JonahQuiz.json"),
	Micah: require("./quizzesByBook/MicahQuiz.json"),
	Nahum: require("./quizzesByBook/NahumQuiz.json"),
	Habakkuk: require("./quizzesByBook/HabakkukQuiz.json"),
	Zephaniah: require("./quizzesByBook/ZephaniahQuiz.json"),
	Haggai: require("./quizzesByBook/HaggaiQuiz.json"),
	Zechariah: require("./quizzesByBook/ZechariahQuiz.json"),
	Malachi: require("./quizzesByBook/MalachiQuiz.json"),
	Matthew: require("./quizzesByBook/MatthewQuiz.json"),
	Mark: require("./quizzesByBook/MarkQuiz.json"),
	Luke: require("./quizzesByBook/LukeQuiz.json"),
	John: require("./quizzesByBook/JohnQuiz.json"),
	Acts: require("./quizzesByBook/ActsQuiz.json"),
	Romans: require("./quizzesByBook/RomansQuiz.json"),
	"1 Corinthians": require("./quizzesByBook/1CorinthiansQuiz.json"),
	"2 Corinthians": require("./quizzesByBook/2CorinthiansQuiz.json"),
	Galatians: require("./quizzesByBook/GalatiansQuiz.json"),
	Ephesians: require("./quizzesByBook/EphesiansQuiz.json"),
	Philippians: require("./quizzesByBook/PhilippiansQuiz.json"),
	Colossians: require("./quizzesByBook/ColossiansQuiz.json"),
	"1 Thessalonians": require("./quizzesByBook/1ThessaloniansQuiz.json"),
	"2 Thessalonians": require("./quizzesByBook/2ThessaloniansQuiz.json"),
	"1 Timothy": require("./quizzesByBook/1TimothyQuiz.json"),
	"2 Timothy": require("./quizzesByBook/2TimothyQuiz.json"),
	Titus: require("./quizzesByBook/TitusQuiz.json"),
	Philemon: require("./quizzesByBook/PhilemonQuiz.json"),
	Hebrews: require("./quizzesByBook/HebrewsQuiz.json"),
	James: require("./quizzesByBook/JamesQuiz.json"),
	"1 Peter": require("./quizzesByBook/1PeterQuiz.json"),
	"2 Peter": require("./quizzesByBook/2PeterQuiz.json"),
	"1 John": require("./quizzesByBook/1JohnQuiz.json"),
	"2 John": require("./quizzesByBook/2JohnQuiz.json"),
	"3 John": require("./quizzesByBook/3JohnQuiz.json"),
	Jude: require("./quizzesByBook/JudeQuiz.json"),
	Revelation: require("./quizzesByBook/RevelationQuiz.json"),
};
